//  This file was generated by CSLA Object Generator - CslaGenFork v4.5
//
// Filename:    DocListGetter
// ObjectType:  DocListGetter
// CSLAType:    UnitOfWork

using System;
using Csla;
using DocStore.Business.Util;

namespace DocStore.Business
{
    public partial class DocListGetter
    {

        #region OnDeserialized actions

        /*/// <summary>
        /// This method is called on a newly deserialized object
        /// after deserialization is complete.
        /// </summary>
        /// <param name="context">Serialization context object.</param>
        protected override void OnDeserialized(System.Runtime.Serialization.StreamingContext context)
        {
            base.OnDeserialized(context);
            // add your custom OnDeserialized actions here.
        }*/

        #endregion

    }
}
