'  This file was generated by CSLA Object Generator - CslaGenFork v4.5
'
' Filename:    FolderInfo
' ObjectType:  FolderInfo
' CSLAType:    ReadOnlyObject

Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports Csla
Imports Csla.Data
Imports DocStore.Business.Util

Namespace DocStore.Business

    ''' <summary>
    ''' Folder basic information (read only object).<br/>
    ''' This is a generated base class of <see cref="FolderInfo"/> business object.
    ''' </summary>
    ''' <remarks>
    ''' This class is an item of <see cref="FolderList"/> collection.
    ''' </remarks>
    <Serializable>
    Public Partial Class FolderInfo
        Inherits ReadOnlyBase(Of FolderInfo)

        #Region " Business Properties "

        ''' <summary>
        ''' Maintains metadata about <see cref="FolderID"/> property.
        ''' </summary>
        Public Shared ReadOnly FolderIDProperty As PropertyInfo(Of Integer) = RegisterProperty(Of Integer)(Function(p) p.FolderID, "Folder ID", -1)
        ''' <summary>
        ''' Gets the Folder ID.
        ''' </summary>
        ''' <value>The Folder ID.</value>
        Public ReadOnly Property FolderID As Integer
            Get
                Return GetProperty(FolderIDProperty)
            End Get
        End Property

        ''' <summary>
        ''' Maintains metadata about <see cref="FolderTypeID"/> property.
        ''' </summary>
        Public Shared ReadOnly FolderTypeIDProperty As PropertyInfo(Of Integer) = RegisterProperty(Of Integer)(Function(p) p.FolderTypeID, "Folder Type ID")
        ''' <summary>
        ''' Gets the Folder Type ID.
        ''' </summary>
        ''' <value>The Folder Type ID.</value>
        Public ReadOnly Property FolderTypeID As Integer
            Get
                Return GetProperty(FolderTypeIDProperty)
            End Get
        End Property

        ''' <summary>
        ''' Maintains metadata about <see cref="FolderRef"/> property.
        ''' </summary>
        Public Shared ReadOnly FolderRefProperty As PropertyInfo(Of String) = RegisterProperty(Of String)(Function(p) p.FolderRef, "FolderRef")
        ''' <summary>
        ''' Gets the FolderRef.
        ''' </summary>
        ''' <value>The FolderRef.</value>
        Public ReadOnly Property FolderRef As String
            Get
                Return GetProperty(FolderRefProperty)
            End Get
        End Property

        ''' <summary>
        ''' Maintains metadata about <see cref="Year"/> property.
        ''' </summary>
        Public Shared ReadOnly YearProperty As PropertyInfo(Of Integer) = RegisterProperty(Of Integer)(Function(p) p.Year, "Folder Year")
        ''' <summary>
        ''' Gets the Folder Year.
        ''' </summary>
        ''' <value>The Folder Year.</value>
        Public ReadOnly Property Year As Integer
            Get
                Return GetProperty(YearProperty)
            End Get
        End Property

        ''' <summary>
        ''' Maintains metadata about <see cref="Subject"/> property.
        ''' </summary>
        Public Shared ReadOnly SubjectProperty As PropertyInfo(Of String) = RegisterProperty(Of String)(Function(p) p.Subject, "Subject")
        ''' <summary>
        ''' Gets the Subject.
        ''' </summary>
        ''' <value>The Subject.</value>
        Public ReadOnly Property Subject As String
            Get
                Return GetProperty(SubjectProperty)
            End Get
        End Property

        ''' <summary>
        ''' Maintains metadata about <see cref="FolderStatusID"/> property.
        ''' </summary>
        Public Shared ReadOnly FolderStatusIDProperty As PropertyInfo(Of Integer) = RegisterProperty(Of Integer)(Function(p) p.FolderStatusID, "Folder Status ID")
        ''' <summary>
        ''' Gets the Folder Status ID.
        ''' </summary>
        ''' <value>The Folder Status ID.</value>
        Public ReadOnly Property FolderStatusID As Integer
            Get
                Return GetProperty(FolderStatusIDProperty)
            End Get
        End Property

        ''' <summary>
        ''' Gets the Folder Type Name.
        ''' </summary>
        ''' <value>The Folder Type Name.</value>
        Public ReadOnly Property FolderTypeName As String
            Get
                Dim result = String.Empty
                If FolderTypeNVL.GetFolderTypeNVL().ContainsKey(FolderTypeID) Then
                    result = FolderTypeNVL.GetFolderTypeNVL().GetItemByKey(FolderTypeID).Value
                End If
                Return result
            End Get
        End Property

        ''' <summary>
        ''' Gets the Folder Status Name.
        ''' </summary>
        ''' <value>The Folder Status Name.</value>
        Public ReadOnly Property FolderStatusName As String
            Get
                Dim result = String.Empty
                If FolderStatusNVL.GetFolderStatusNVL().ContainsKey(FolderStatusID) Then
                    result = FolderStatusNVL.GetFolderStatusNVL().GetItemByKey(FolderStatusID).Value
                End If
                Return result
            End Get
        End Property

        #End Region

        #Region " Factory Methods "

        ''' <summary>
        ''' Factory method. Loads a <see cref="FolderInfo"/> object from the given SafeDataReader.
        ''' </summary>
        ''' <param name="dr">The SafeDataReader to use.</param>
        ''' <returns>A reference to the fetched <see cref="FolderInfo"/> object.</returns>
        Friend Shared Function GetFolderInfo(dr As SafeDataReader) As FolderInfo
            Dim obj As FolderInfo = New FolderInfo()
            obj.Fetch(dr)
            Return obj
        End Function

        #End Region

        #Region " Constructor "

        ''' <summary>
        ''' Initializes a new instance of the <see cref="FolderInfo"/> class.
        ''' </summary>
        ''' <remarks> Do not use to create a Csla object. Use factory methods instead.</remarks>
        <System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)>
        Public Sub New()
            ' Use factory methods and do not use direct creation.
        End Sub

        #End Region

        #Region " Data Access "

        ''' <summary>
        ''' Loads a <see cref="FolderInfo"/> object from the given SafeDataReader.
        ''' </summary>
        ''' <param name="dr">The SafeDataReader to use.</param>
        Private Sub Fetch(dr As SafeDataReader)
            ' Value properties
            LoadProperty(FolderIDProperty, dr.GetInt32("FolderID"))
            LoadProperty(FolderTypeIDProperty, dr.GetInt32("FolderTypeID"))
            LoadProperty(FolderRefProperty, dr.GetString("FolderRef"))
            LoadProperty(YearProperty, dr.GetInt32("Year"))
            LoadProperty(SubjectProperty, dr.GetString("Subject"))
            LoadProperty(FolderStatusIDProperty, dr.GetInt32("FolderStatusID"))
            Dim args As New DataPortalHookArgs(dr)
            OnFetchRead(args)
        End Sub

        #End Region

        #Region " DataPortal Hooks "

        ''' <summary>
        ''' Occurs after the low level fetch operation, before the data reader is destroyed.
        ''' </summary>
        Partial Private Sub OnFetchRead(args As DataPortalHookArgs)
        End Sub

        #End Region

    End Class
End Namespace
