DBCC CHECKIDENT ('Level_1', RESEED, 0)
DBCC CHECKIDENT ('Level_1', RESEED)

DBCC CHECKIDENT ('Level_1_1', RESEED, 0)
DBCC CHECKIDENT ('Level_1_1', RESEED)

DBCC CHECKIDENT ('Level_1_1_1', RESEED, 0)
DBCC CHECKIDENT ('Level_1_1_1', RESEED)

DBCC CHECKIDENT ('Level_1_1_1_1', RESEED, 0)
DBCC CHECKIDENT ('Level_1_1_1_1', RESEED)

DBCC CHECKIDENT ('Level_1_1_1_1_1', RESEED, 0)
DBCC CHECKIDENT ('Level_1_1_1_1_1', RESEED)

DBCC CHECKIDENT ('Level_1_1_1_1_1_1', RESEED, 0)
DBCC CHECKIDENT ('Level_1_1_1_1_1_1', RESEED)


