//  This file was generated by CSLA Object Generator - CslaGenFork v4.5
//
// Filename:    DocClassEditColl
// ObjectType:  DocClassEditColl
// CSLAType:    DynamicEditableRootCollection

using System;
using System.Data;
using System.Data.SqlClient;
using Csla;
using Csla.Data;
using DocStore.Business.Util;
using Csla.Rules;
using Csla.Rules.CommonRules;

namespace DocStore.Business
{

    /// <summary>
    /// DocClassEditColl (dynamic root list).<br/>
    /// This is a generated base class of <see cref="DocClassEditColl"/> business object.
    /// </summary>
    /// <remarks>
    /// The items of the collection are <see cref="DocClassEdit"/> objects.
    /// </remarks>
    [Serializable]
    public partial class DocClassEditColl : DynamicBindingListBase<DocClassEdit>
    {

        #region Collection Business Methods

        /// <summary>
        /// Adds a new <see cref="DocClassEdit"/> item to the collection.
        /// </summary>
        /// <param name="item">The item to add.</param>
        /// <exception cref="System.Security.SecurityException">if the user isn't authorized to add items to the collection.</exception>
        /// <exception cref="ArgumentException">if the item already exists in the collection.</exception>
        public new void Add(DocClassEdit item)
        {
            if (!CanAddObject())
                throw new System.Security.SecurityException("User not authorized to create a DocClassEdit.");

            if (Contains(item.DocClassID))
                throw new ArgumentException("DocClassEdit already exists.");

            base.Add(item);
        }

        /// <summary>
        /// Removes a <see cref="DocClassEdit"/> item from the collection.
        /// </summary>
        /// <param name="item">The item to remove.</param>
        /// <returns><c>true</c> if the item was removed from the collection, otherwise <c>false</c>.</returns>
        /// <exception cref="System.Security.SecurityException">if the user isn't authorized to remove items from the collection.</exception>
        public new bool Remove(DocClassEdit item)
        {
            if (!CanDeleteObject())
                throw new System.Security.SecurityException("User not authorized to remove a DocClassEdit.");

            return base.Remove(item);
        }

        /// <summary>
        /// Adds a new <see cref="DocClassEdit"/> item to the collection.
        /// </summary>
        /// <returns>The new DocClassEdit item added to the collection.</returns>
        public DocClassEdit Add()
        {
            var item = DocClassEdit.NewDocClassEdit();
            Add(item);
            return item;
        }

        /// <summary>
        /// Asynchronously adds a new <see cref="DocClassEdit"/> item to the collection.
        /// </summary>
        public void BeginAdd()
        {
            DocClassEdit docClassEdit = null;
            DocClassEdit.NewDocClassEdit((o, e) =>
                {
                    if (e.Error != null)
                        throw e.Error;
                    else
                        docClassEdit = e.Object;
                });
            Add(docClassEdit);
        }

        /// <summary>
        /// Removes a <see cref="DocClassEdit"/> item from the collection.
        /// </summary>
        /// <param name="docClassID">The DocClassID of the item to be removed.</param>
        public void Remove(int docClassID)
        {
            foreach (var docClassEdit in this)
            {
                if (docClassEdit.DocClassID == docClassID)
                {
                    Remove(docClassEdit);
                    break;
                }
            }
        }

        /// <summary>
        /// Determines whether a <see cref="DocClassEdit"/> item is in the collection.
        /// </summary>
        /// <param name="docClassID">The DocClassID of the item to search for.</param>
        /// <returns><c>true</c> if the DocClassEdit is a collection item; otherwise, <c>false</c>.</returns>
        public bool Contains(int docClassID)
        {
            foreach (var docClassEdit in this)
            {
                if (docClassEdit.DocClassID == docClassID)
                {
                    return true;
                }
            }
            return false;
        }

        #endregion

        #region Factory Methods

        /// <summary>
        /// Factory method. Creates a new <see cref="DocClassEditColl"/> collection.
        /// </summary>
        /// <returns>A reference to the created <see cref="DocClassEditColl"/> collection.</returns>
        public static DocClassEditColl NewDocClassEditColl()
        {
            return DataPortal.Create<DocClassEditColl>();
        }

        /// <summary>
        /// Factory method. Loads a <see cref="DocClassEditColl"/> collection.
        /// </summary>
        /// <returns>A reference to the fetched <see cref="DocClassEditColl"/> collection.</returns>
        public static DocClassEditColl GetDocClassEditColl()
        {
            return DataPortal.Fetch<DocClassEditColl>();
        }

        /// <summary>
        /// Factory method. Asynchronously creates a new <see cref="DocClassEditColl"/> collection.
        /// </summary>
        /// <param name="callback">The completion callback method.</param>
        public static void NewDocClassEditColl(EventHandler<DataPortalResult<DocClassEditColl>> callback)
        {
            DocClassEditCollGetter.NewDocClassEditCollGetter((o, e) =>
            {
                callback(o, new DataPortalResult<DocClassEditColl>(e.Object.DocClassEditColl, e.Error, null));
            });
        }

        /// <summary>
        /// Factory method. Asynchronously loads a <see cref="DocClassEditColl"/> collection.
        /// </summary>
        /// <param name="callback">The completion callback method.</param>
        public static void GetDocClassEditColl(EventHandler<DataPortalResult<DocClassEditColl>> callback)
        {
            DocClassEditCollGetter.GetDocClassEditCollGetter((o, e) =>
            {
                callback(o, new DataPortalResult<DocClassEditColl>(e.Object.DocClassEditColl, e.Error, null));
            });
        }

        #endregion

        #region Constructor

        /// <summary>
        /// Initializes a new instance of the <see cref="DocClassEditColl"/> class.
        /// </summary>
        /// <remarks> Do not use to create a Csla object. Use factory methods instead.</remarks>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public DocClassEditColl()
        {
            // Use factory methods and do not use direct creation.

            var rlce = RaiseListChangedEvents;
            RaiseListChangedEvents = false;
            AllowNew = DocClassEditColl.CanAddObject();
            AllowEdit = DocClassEditColl.CanEditObject();
            AllowRemove = DocClassEditColl.CanDeleteObject();
            RaiseListChangedEvents = rlce;
        }

        #endregion

        #region Object Authorization

        /// <summary>
        /// Adds the object authorization rules.
        /// </summary>
        protected static void AddObjectAuthorizationRules()
        {
            BusinessRules.AddRule(typeof (DocClassEditColl), new IsInRole(AuthorizationActions.CreateObject, "Admin"));
            BusinessRules.AddRule(typeof (DocClassEditColl), new IsInRole(AuthorizationActions.GetObject, "User"));
            BusinessRules.AddRule(typeof (DocClassEditColl), new IsInRole(AuthorizationActions.EditObject, "Admin"));
            BusinessRules.AddRule(typeof (DocClassEditColl), new IsInRole(AuthorizationActions.DeleteObject, "Admin"));

            AddObjectAuthorizationRulesExtend();
        }

        /// <summary>
        /// Allows the set up of custom object authorization rules.
        /// </summary>
        static partial void AddObjectAuthorizationRulesExtend();

        /// <summary>
        /// Checks if the current user can create a new DocClassEditColl object.
        /// </summary>
        /// <returns><c>true</c> if the user can create a new object; otherwise, <c>false</c>.</returns>
        public static bool CanAddObject()
        {
            return BusinessRules.HasPermission(Csla.Rules.AuthorizationActions.CreateObject, typeof(DocClassEditColl));
        }

        /// <summary>
        /// Checks if the current user can retrieve DocClassEditColl's properties.
        /// </summary>
        /// <returns><c>true</c> if the user can read the object; otherwise, <c>false</c>.</returns>
        public static bool CanGetObject()
        {
            return BusinessRules.HasPermission(Csla.Rules.AuthorizationActions.GetObject, typeof(DocClassEditColl));
        }

        /// <summary>
        /// Checks if the current user can change DocClassEditColl's properties.
        /// </summary>
        /// <returns><c>true</c> if the user can update the object; otherwise, <c>false</c>.</returns>
        public static bool CanEditObject()
        {
            return BusinessRules.HasPermission(Csla.Rules.AuthorizationActions.EditObject, typeof(DocClassEditColl));
        }

        /// <summary>
        /// Checks if the current user can delete a DocClassEditColl object.
        /// </summary>
        /// <returns><c>true</c> if the user can delete the object; otherwise, <c>false</c>.</returns>
        public static bool CanDeleteObject()
        {
            return BusinessRules.HasPermission(Csla.Rules.AuthorizationActions.DeleteObject, typeof(DocClassEditColl));
        }

        #endregion

        #region Data Access

        /// <summary>
        /// Loads a <see cref="DocClassEditColl"/> collection from the database.
        /// </summary>
        protected void DataPortal_Fetch()
        {
            using (var ctx = ConnectionManager<SqlConnection>.GetManager(Database.DocStoreConnection, false))
            {
                using (var cmd = new SqlCommand("GetDocClassEditColl", ctx.Connection))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    var args = new DataPortalHookArgs(cmd);
                    OnFetchPre(args);
                    LoadCollection(cmd);
                    OnFetchPost(args);
                }
            }
        }

        private void LoadCollection(SqlCommand cmd)
        {
            using (var dr = new SafeDataReader(cmd.ExecuteReader()))
            {
                Fetch(dr);
            }
        }

        /// <summary>
        /// Loads all <see cref="DocClassEditColl"/> collection items from the given SafeDataReader.
        /// </summary>
        /// <param name="dr">The SafeDataReader to use.</param>
        private void Fetch(SafeDataReader dr)
        {
            var rlce = RaiseListChangedEvents;
            RaiseListChangedEvents = false;
            while (dr.Read())
            {
                Add(DocClassEdit.GetDocClassEdit(dr));
            }
            RaiseListChangedEvents = rlce;
        }

        #endregion

        #region DataPortal Hooks

        /// <summary>
        /// Occurs after setting query parameters and before the fetch operation.
        /// </summary>
        partial void OnFetchPre(DataPortalHookArgs args);

        /// <summary>
        /// Occurs after the fetch operation (object or collection is fully loaded and set up).
        /// </summary>
        partial void OnFetchPost(DataPortalHookArgs args);

        #endregion

    }
}
