//  This file was generated by CSLA Object Generator - CslaGenFork v4.5
//
// Filename:    DocStatusColl
// ObjectType:  DocStatusColl
// CSLAType:    EditableRootCollection

using System;
using Csla;
using DocStore.Business.Util;

namespace DocStore.Business
{
    public partial class DocStatusColl
    {

        #region OnDeserialized actions

        /*/// <summary>
        /// This method is called on a newly deserialized object
        /// after deserialization is complete.
        /// </summary>
        protected override void OnDeserialized()
        {
            base.OnDeserialized();
            // add your custom OnDeserialized actions here.
        }*/

        #endregion

        #region Implementation of DataPortal Hooks

        //partial void OnFetchPre(DataPortalHookArgs args)
        //{
        //    throw new NotImplementedException();
        //}

        //partial void OnFetchPost(DataPortalHookArgs args)
        //{
        //    throw new NotImplementedException();
        //}

        #endregion

    }
}
